# Generated by Django 5.2.15 on 2026-06-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('lenguaje', 'Lenguajes'), ('framework', 'Frameworks'), ('bd', 'Bases de Datos'), ('herramienta', 'Herramientas'), ('automatizacion', 'Automatizacion')], max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(default=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['categoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('descripcion_larga', models.TextField(blank=True)),
                ('tecnologias', models.CharField(max_length=300)),
                ('url_github', models.URLField(blank=True)),
                ('url_demo', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', '-fecha'],
            },
        ),
    ]
